[package]
name = "coop"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.0.0-beta", features = [] }

[dependencies]
nostr-sdk = { git = "https://github.com/rust-nostr/nostr", features = [
	"sqlite",
] }
tauri = { version = "2.0.0-beta", features = [
	"tray-icon",
	"macos-private-api",
	"protocol-asset",
] }
tauri-specta = { git = "https://github.com/reyamir/tauri-specta", branch = "feat/tauri-v2", features = [
	"typescript",
] }
tauri-plugin-devtools = "2.0.0-beta"
tauri-plugin-prevent-default = "0.2"
tauri-plugin-os = "2.0.0-beta"
tauri-plugin-clipboard-manager = "2.0.0-beta"
tauri-plugin-dialog = "2.0.0-beta"
tauri-plugin-shell = "2.0.0-beta"
tauri-plugin-decorum = "0.1.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
keyring = { version = "3", features = [
	"apple-native",
	"windows-native",
	"linux-native",
] }
keyring-search = "1.2.0"
itertools = "0.13.0"
futures = "0.3.30"
specta = "^2.0.0-rc.12"

[target.'cfg(target_os = "macos")'.dependencies]
border = { git = "https://github.com/ahkohd/tauri-toolkit", branch = "v2" }

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
incremental = false
opt-level = "z"
strip = true
rpath = false
debug = false
debug-assertions = false
overflow-checks = false
