[package]
name = "app_state"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
common = { path = "../common" }
state = { path = "../state" }
ui = { path = "../ui" }

gpui.workspace = true
nostr-sdk.workspace = true
