[workspace]
members = ["crates/*"]
default-members = ["crates/app"]
resolver = "2"

[workspace.dependencies]
coop = { path = "crates/*" }

# UI
gpui = { git = "https://github.com/zed-industries/zed" }
reqwest_client = { git = "https://github.com/zed-industries/zed" }

# Nostr
nostr-relay-builder = { git = "https://github.com/rust-nostr/nostr" }
nostr-sdk = { git = "https://github.com/rust-nostr/nostr", features = [
	"lmdb",
	"all-nips",
] }

smol = "1"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "5.0"
itertools = "0.13.0"
futures = "0.3.30"
chrono = "0.4.38"
tracing = "0.1.40"
anyhow = "1.0.44"
smallvec = "1.13.2"
rust-embed = "8.5.0"
keyring-search = "1.2.0"
keyring = { version = "3", features = [
	"apple-native",
	"windows-native",
	"sync-secret-service",
] }
