name = "coop"
product-name = "Coop"
identifier = "su.reya.coop"
version = "0.1.0"
resources = ["src", "icons/*", "Cargo.toml", "../../README.md"]
icons = [
  "icons/32x32.png",
  "icons/128x128.png",
  "icons/128x128@2x.png",
  "icons/icon.icns",
  "icons/icon.ico",
]
before-packaging-command = "cargo build --release"
