name = "coop"
description = "Coop is a cross-platform Nostr client designed for secure communication focus on simplicity and customizability."
product-name = "Coop"
identifier = "su.reya.coop"
resources = ["assets/*/*", "Cargo.toml", "./LICENSE", "./README.md"]
icons = [
  "crates/coop/resources/32x32.png",
  "crates/coop/resources/128x128.png",
  "crates/coop/resources/128x128@2x.png",
  "crates/coop/resources/app-icon.icns",
  "crates/coop/resources/app-icon.png",
  "crates/coop/resources/app-icon.ico",
]
before-packaging-command = "cargo build --release"
out-dir = "./target/release"
binaries = [
	{ path = "coop", main = true },
]
