[package]
name = "coop"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "coop"
path = "src/main.rs"

[dependencies]
gpui.workspace = true
components.workspace = true
tokio.workspace = true
nostr-sdk.workspace = true

client = { version = "0.1.0", path = "../client" }

keyring-search = "1.2.0"
keyring-lib = { version = "1.0.2", features = ["tokio", "derive"] }
