[package]
name = "coop"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "coop"
path = "src/main.rs"

[dependencies]
gpui.workspace = true
components.workspace = true
tokio.workspace = true
nostr-sdk.workspace = true
keyring-search.workspace = true
keyring.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
reqwest_client.workspace = true

client = { version = "0.1.0", path = "../client" }
rust-embed = "8.5.0"
env_logger = "0.11.5"
