[package]
name = "coop"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "coop"
path = "src/main.rs"

[dependencies]
ui = { path = "../ui" }

gpui.workspace = true
reqwest_client.workspace = true

tokio.workspace = true
nostr-sdk.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
itertools.workspace = true
chrono.workspace = true
dirs.workspace = true
rust-embed.workspace = true
smol.workspace = true

tracing-subscriber = { version = "0.3.18", features = ["fmt"] }
random_name_generator = "0.3.6"
