[package]
name = "common"
version = "0.0.0"
edition.workspace = true
publish.workspace = true

[dependencies]
global = { path = "../global" }

gpui.workspace = true
nostr-sdk.workspace = true
anyhow.workspace = true
itertools.workspace = true
chrono.workspace = true
smallvec.workspace = true

random_name_generator = "0.3.6"
qrcode-generator = "5.0.0"
